package models

const (
	HeaderServerName          = "server-name"
	HeaderAuthorization       = "authorization"
	HeaderXRequestID          = "x-request-id"
	HeaderXCorrelationID      = "x-correlation-id"
	HeaderXIPAddress          = "x-ip-address"
	HeaderXForwardedFor       = "x-forwarded-for"
	HeaderXForwardedProto     = "x-forwarded-proto"
	HeaderXForwardedHost      = "x-forwarded-host"
	HeaderXClientVersion      = "x-client-version"
	HeaderXClientID           = "x-client-id"
	HeaderXDeviceID           = "x-device-id"
	HeaderXSessionID          = "x-session-id"
	HeaderXUserID             = "x-user-id"
	HeaderXTraceID            = "x-trace-id"
	HeaderXSpanID             = "x-span-id"
	HeaderXRoles              = "x-roles"
	HeaderXIsOAuth            = "x-is-oauth"
	HeaderXSessionCreatedAt   = "x-session-created-at"
	HeaderXSessionExpiresAt   = "x-session-expires-at"
	HeaderXLastActivityAt     = "x-last-activity-at"
	XTimezone                 = "x-timezone"
	HeaderXProps              = "x-props"
	HeaderXAPIKey             = "x-api-key"
	HeaderXCSRFToken          = "x-csrf-token"
	HeaderXRateLimitLimit     = "x-rate-limit-limit"
	HeaderXRateLimitRemaining = "x-rate-limit-remaining"
	HeaderXRateLimitReset     = "x-rate-limit-reset"
	// Standard headers
	HeaderContentType    = "content-type"
	HeaderUserAgent      = "user-agent"
	HeaderAccept         = "accept"
	HeaderAcceptLanguage = "accept-language"
	HeaderAcceptEncoding = "accept-encoding"
	HeaderCacheControl   = "cache-control"
	// gRPC specific
	HeaderGRPCWeb      = "x-grpc-web"
	HeaderGRPCEncoding = "grpc-encoding"
	HeaderGRPCMessage  = "grpc-message"
	HeaderGRPCStatus   = "grpc-status"
)
